### PR TITLE
add presets to html tag integrator

### PR DESCRIPTION
**Pull request by solverat**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #37

### CODE REVIEW

**Comment by aarongerig** [comment]
@solverat Have you checked if the meta tags actually get printed in the HTML output? Just now I created the PR for V1 and tried to test the outcome in the HTML source code. Unfortunately the `HeadMeta` class always looses track of the raw HTML tags we are adding via the HTML Tag Integrator.

**Comment by solverat** [comment]
Yes. My Head:

```twig
<head>
    {% block metadata %}
        {{ pimcore_head_title() }}
        {{ pimcore_head_meta() }}
        {{ pimcore_head_link() }}
    {% endblock metadata %}
</head>
```

**Comment by aarongerig** [comment]
I have the exact same head and only the `<meta name="description" content="...">` gets output. I guess there has to be a difference between Pimcore 6 and Pimcore 10 then. 🤔

PS: The HTML Tag Integrator without the preset feature also does not work in V1 / Pimcore 6.

**Comment by solverat** [comment]
Should also work for P6. Did that in about 5000 P6 projects! :) 

So it would be nice to know if you've figured it out!

**Pull request merged**
